[project]
name = "genial"
version = "0.1.0"
description = "Conteúdo do curso Genetic and Evolutionary Nature-Inspired ALgorithms do LID-UFPA."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "mealpy (>=3.0.3,<4.0.0)",
    "scikit-learn (>=1.7.2,<2.0.0)",
    "ipykernel (>=6.30.1,<7.0.0)",
    "pyomo (>=6.9.4,<7.0.0)",
    "pandas>=2.3.3",
    "rich>=14.2.0",
]

[tool.ruff]
indent-width = 4
line-length = 100
select = [
  "ALL",
]
ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D107",
  "I001",
  "T201",
  "E501",
  "PLR0913",
  "S311"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 100
